language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: Naterade.xcodeproj
xcode_scheme: 
    - LoopTests
before_script:
    - carthage bootstrap
script:
    - xcodebuild -project Naterade.xcodeproj -scheme LoopTests -sdk iphonesimulator9.3 test
